version: "1.2"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    networks:
      - coolify

networks:
  my_network:
    external: true