version: "1.2"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-router.rule=Host(`coolify.io`) && PathPrefix(`/`)"
      - "traefik.http.routers.server-router.entryPoints=http"


networks:
  my_network:
    external: true