import "@ui/globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import type {ReactNode, JSX} from "react";
import Providers from "@/app/providers";

const inter = Inter({subsets: ["latin"]});
// const queryClient = useQueryClient();

export const metadata: Metadata = {
    title: "Docs",
    description: "Generated by create turbo",
};

export default function RootLayout({children}: {
    children: ReactNode;
}): JSX.Element {
    return (
        <html lang="ru">
        <body className={inter.className}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
